source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'mysql2'
gem 'devise'
gem 'newrelic_rpm'

# https://github.com/norman/friendly_id
gem 'friendly_id' 
gem 'auto_strip_attributes', '~> 2.0'
gem 'sass-rails', '~> 4.0.1'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.0.4'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.0.1'

gem 'aws-sdk'
gem 'paperclip', "~> 4.1" #, github: 'thoughtbot/paperclip' # For handling image uploads
gem 'dynamoid'

# bundle exec rake doc:rails generates the API under doc/api.
group :doc do  
  gem 'sdoc', require: false
end